'''
Shadow API Generator
~~~~~~~~~~~~~~~~~~~~

Automatically generates standalone Python scripts from captured requests.
'''

import pprint

def generate_script(response) -> str:
    '''
    Generates a standalone Python script that replicates the request
    associated with the given response.
    '''
    data = response._request_data
    if not data:
        return "# Error: No request metadata found for this response."

    url = data.get('requestUrl')
    method = data.get('requestMethod', 'GET').lower()
    headers = data.get('headers', {})
    cookies = data.get('requestCookies', [])
    body = data.get('requestBody')
    proxy = data.get('proxyUrl')
    
    # Handle TLS fingerprint
    if 'tlsClientIdentifier' in data:
        client_id = data['tlsClientIdentifier']
        client_setup = f"browser='{client_id.split('_')[0]}', version={client_id.split('_')[-1]}"
    else:
        # Custom TLS string
        client_setup = f"ja3_string='{data.get('customTlsClient', {}).get('ja3String')}'"

    # Format headers and cookies for the script
    headers_str = pprint.pformat(headers, indent=4)
    cookies_str = pprint.pformat(cookies, indent=4)
    
    script = f"""import hrequests

# Replicated headers
headers = {headers_str}

# Replicated cookies
cookies = {cookies_str}

def execute_replicated_request():
    '''
    Automatically generated by LordRequests Shadow API Generator.
    This script replicates the exact TLS fingerprint and network patterns
    of the original captured request.
    '''
    session = hrequests.Session({client_setup})
    
    response = session.request(
        method='{method.upper()}',
        url='{url}',
        headers=headers,
        cookies=cookies,
        proxy={repr(proxy)},
        data={repr(body) if body else 'None'},
        verify={not data.get('insecureSkipVerify', False)}
    )
    
    return response

if __name__ == '__main__':
    resp = execute_replicated_request()
    print(f"Status Code: {{resp.status_code}}")
    print(f"Response Snippet: {{resp.text[:200]}}...")
"""
    return script
